//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSStringTemplate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSStringTemplate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to compile template. Engine message: {0}.
        /// </summary>
        internal static string CompiletimeExceptionWrapper {
            get {
                return ResourceManager.GetString("CompiletimeExceptionWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing argument &apos;{0}&apos; in template &apos;{1}&apos;, skipping..
        /// </summary>
        internal static string DebugArgumentNotFound {
            get {
                return ResourceManager.GetString("DebugArgumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching attribute found for parameter &apos;{0}&apos; in template &apos;{1}&apos;..
        /// </summary>
        internal static string DebugAttributeNotFound {
            get {
                return ResourceManager.GetString("DebugAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was received while invoking method &apos;{0}&apos; for attribute &apos;{1}&apos;..
        /// </summary>
        internal static string DebugInvokePropertyLikeMethodException {
            get {
                return ResourceManager.GetString("DebugInvokePropertyLikeMethodException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find property &apos;{0}&apos; while processing template &apos;{1}&apos;..
        /// </summary>
        internal static string DebugPropertyNotFound {
            get {
                return ResourceManager.GetString("DebugPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anonymous.
        /// </summary>
        internal static string DefaultTemplateName {
            get {
                return ResourceManager.GetString("DefaultTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while processing template &quot;{0}&quot;.  Engine message: {1}.
        /// </summary>
        internal static string RuntimeExceptionWrapper {
            get {
                return ResourceManager.GetString("RuntimeExceptionWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find template &apos;{0}&apos;. (Found: {1}).
        /// </summary>
        internal static string TemplateNotFound {
            get {
                return ResourceManager.GetString("TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception from StringTemplate, please file an issue on GitHub. Engine message: {0}.
        /// </summary>
        internal static string UnhandledErrorMessage {
            get {
                return ResourceManager.GetString("UnhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added parameter &apos;{0}&apos; to template &apos;{1}&apos;..
        /// </summary>
        internal static string VerboseAddedParameter {
            get {
                return ResourceManager.GetString("VerboseAddedParameter", resourceCulture);
            }
        }
    }
}
